name: Rust

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --all
    - name: Upload artifacts (daemon)
      uses: actions/upload-artifact@v2
      with:
        name: cartel-daemon
        path: target/release/daemon
        retention-days: 5
    - name: Upload artifacts (client)
      uses: actions/upload-artifact@v2
      with:
        name: cartel
        path: target/release/client
        retention-days: 5    
